model = dict(
    type='StyleGAN',
    resolution=1024,
    latent_channels=512,
    pretrained=None,
    generator=dict(
        type='StyleGANGen',
        mapping=dict(
            type='StyleMapping',
            in_channels=512,
            out_channels=512,
            num_layers=8,
            activation=dict(
                type='LeakyReLU',
                alpha=0.2
            )
        ),
        synthesis=dict(
            type='StyleSynthesis',
            in_channels=512,
            style_channels=512,
            activation=dict(
                type='LeakyReLU',
                alpha=0.2
            )
        )
    ),
    discriminator=dict(
        type='ProGANDisc',
        max_channels=512,
        activation=dict(
            type='LeakyReLU',
            alpha=0.2
        )
    ),
    loss_gen=dict(
        type='ProGANLossGen',
    ),
    loss_disc=dict(
        type='ProGANLossDisc',
    )
)
